#!/sbin/sh
# Busybox Installer Script: Recovery Flashable Zip
# osm0sis @ xda-developers

ui_print() {
  if $BOOTMODE; then
    echo "$1"
  else
    echo -n -e "ui_print $1\n" >> /proc/self/fd/$OUTFD
    echo -n -e "ui_print\n" >> /proc/self/fd/$OUTFD
  fi
}
abort() {
  ui_print "   ! Busybox has not been installed";
  ui_print " ";
  exit 1;
}

case $ABILONG in
  arm64*) arch=arm64;;
  arm*) arch=arm;;
  x86_64*) arch=x86_64;;
  x86*) arch=x86;;
  mips64*) arch=mips64;;
  mips*) arch=mips;;
  *) ui_print "! Unknown architecture: $ABILONG"; abort;;
esac;
ui_print "- Using architecture: $arch";

suimg=$(ls /data/su.img || ls /cache/su.img || ls /data/magisk.img || ls /cache/magisk.img) 2>/dev/null;
mnt=/$(basename $suimg .img);
if [ "$suimg" ]; then
  test "$mnt" == "/magisk" && magisk=/busybox-ndk/system;
  test -d $mnt$magisk/xbin -o "$magisk" && target=$mnt$magisk/xbin || target=$mnt/bin;
else
  target=/system/xbin
fi;
ui_print "- Using path: $target";
mkdir -p $target;
cp -f $INSTALLER/busybox/busybox-$arch $target/busybox;
chown 0:0 "$target/busybox";
chmod 755 "$target/busybox";
if [ "$magisk" ]; then
  cp -f $INSTALLER/busybox/module.prop /magisk/busybox-ndk/;
  touch /magisk/busybox-ndk/auto_mount;
fi;

ui_print "- Cleaning...";
cleanup="$target";
if [ "$target" == "$mnt$magisk/xbin" -a -f "$mnt$magisk/bin/busybox" ]; then
  $target/busybox rm -f $mnt$magisk/bin/busybox;
  cleanup="$mnt$magisk/bin $target";
fi;
for dir in $cleanup; do
  cd $dir;
  for i in $(ls -al `find -type l` | $target/busybox awk '{ print $(NF-2) ":" $NF }'); do
    case $(echo $i | $target/busybox cut -d: -f2) in
      *busybox) list="$list $dir/$(echo $i | $target/busybox cut -d: -f1)";;
    esac;
  done;
done;
$target/busybox rm -f $list;

ui_print "- Creating symlinks...";
for applet in `$target/busybox --list`; do
  if [ "$target" == "$mnt$magisk/bin" ]; then
    sysbin="$(ls /system/bin)";
    case $sysbin in
      *$applet*) ;;
      *) $target/busybox ln -sf busybox $applet;;
    esac;
  else
    $target/busybox ln -sf busybox $applet;
  fi;
done;

ui_print "- Busybox has been successfully installed";
exit 0;
